spring.application.name=personallibrary

spring.datasource.url=jdbc:postgresql://localhost:5432/personallibrary
spring.datasource.username=user
spring.datasource.password=password

# Performance
spring.threads.virtual.enabled=true

# Development Speed (Auto-reload Thymeleaf templates)
spring.thymeleaf.cache=false
spring.sql.init.mode=always

spring.mvc.hiddenmethod.filter.enabled=true
